config/routes.rb
Rails.application.routes.draw do
  root "check#index"

  resources :check, only: [:index, :show] do
    member do
      post :evaluate
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/check.rb
class Check
  def solution
  end

  def model_name
    OpenStruct.new(param_key: 'check')
  end

  def to_key; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/check_controller.rb
class CheckController < ApplicationController
  CHECKERS_PATH = Rails.root.join('lib/checkers') # TODO: move to global constants

  def index
    @tasks = Dir.entries(CHECKERS_PATH).filter_map do |task_name|
      next if task_name.starts_with?('.')
      meta_path = File.join(CHECKERS_PATH, task_name, 'meta.yml')

      next if File.exists?(meta_path) && YAML.load(File.read(meta_path)).fetch('public') == false

      task_name
    end.sort
  end

  def show
    @test_content = File.read(task_path)[/RSpec.+/m]
    @template = params[:template] || File.read(template_path)
    @description = YAML.load(File.read(meta_path)).fetch('description') if File.exists?(meta_path)
    @error_message = params[:error_message]
  end

  def evaluate
    Object.const_set('Checker', Module.new)
    begin
      ::Checker.module_eval(provided_solution)
    rescue SyntaxError
      nil
    end
    test_evaluation = CheckRunner.call(task_path: task_path)
    Object.send(:remove_const, 'Checker')

    redirect_to action: :show,
                result: test_evaluation.result.zero? ? 'success' : 'failed',
                template: provided_solution.gsub(/File2/, 'File').gsub(/CSV2/, 'CSV'),
                error_message: test_evaluation.outputs
  end

  private

  def task_path
    File.join(CHECKERS_PATH, task_name, 'spec.rb')
  end

  def template_path
    File.join(CHECKERS_PATH, task_name, 'template.rb')
  end

  def meta_path
    File.join(CHECKERS_PATH, task_name, 'meta.yml')
  end

  def task_name
    params[:id]
  end

  def provided_solution
    stop_list = %w[
      exec system eval send byebug binding pry write IO FileUtils FileTest Dir DIR __ @@ `
      Rails config Config ENV ActiveRecord Application Controller RSpec
    ].freeze
    guard_regexp = Regexp.new(stop_list.join('|'))

    params.dig('check', 'solution')
          .gsub(guard_regexp, '###')
          .gsub(/File/, 'File2')
          .gsub(/CSV/, 'CSV2')
  end

  class CheckRunner
    def self.call(task_path:)
      require 'rspec/core'

      error_stream = StringIO.new
      output_stream = StringIO.new

      result = RSpec::Core::Runner.run([task_path, '--format', 'json'], error_stream, output_stream)
      RSpec.reset

      errors = JSON.parse(error_stream.string, { object_class: OpenStruct }) if error_stream.string.present?
      outputs = JSON.parse(output_stream.string, { object_class: OpenStruct }) if output_stream.string.present?

      OpenStruct.new(result: result, errors: errors, outputs: formatted_output(outputs))
    end

    def self.formatted_output(output)
      examples_result = output.examples.map.with_index(1) do |example, index|
        description = index.to_s + ': ' + example.description.titleize
        next (description + ': Passed') if example.status == 'passed'

        description + "\n" + example.exception.message
      end

      examples_result.join("\n\n") + "\n\n" + output.summary_line
    end

    # Other approach is to use Mini-tests:
    # https://docs.knapsackpro.com/2018/how-to-run-tests-in-minitest-continuously-with-dynamic-test-files-loading
    #
    # Check Travis
    # How to build custom code in the container?
    #
    # It might be helpful:
    # https://github.com/heroku/logplex/blob/master/.travis.yml
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_helper.rb
module CheckHelper
end

app/views/check/_show_test.html.haml
- url = evaluate_check_url(id: params[:id])
= simple_form_for Check.new, url: url, method: :post do |f|
  = f.input :solution,
            as: :text,
            input_html: { rows: 15, value: @template },
            label: 'Modify this class to make specs green:'

  - if params[:result] == 'success'
    .alert.alert-success Tests passed.
  - if params[:result] == 'failed'
    .alert.alert-danger
      Tests failed.
      %pre{ style: "white-space: pre-wrap" }
        = @error_message

  = f.button :submit, 'Check', class: 'btn btn-primary mt-4'

app/views/check/index.html.haml
.row
  .col-6
    %br
    .list-group.tasks-index
      - @tasks.each_with_index do |task, index|
        = link_to check_url(id: task), class: 'list-group-item list-group-item-action' do
          %h4= "#{index + 1}. #{task.humanize}"

app/views/check/show.html.haml
%h4= params[:id].humanize

%pre{ style: "background-color: white; padding: 8px; border: gray solid 1px;" }
  - if @description.present?
    = @description.join('<br>').html_safe
  - else
    Check specs in the right panel and implement the code to make tests green

%br

.row
  .col-6
    = turbo_frame_tag 'show_test' do
      = render 'check/show_test'
  .col-6
    .form-group
      .label Test specs
      .form-control{ style: "background-color: antiquewhite;" }
        %pre
          = @test_content

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Task Checker
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
    = favicon_link_tag asset_path('favicon.png')
  %body.bg-light
    .container.py-5
      = link_to 'Home', root_url

      .text-center
        %h2 Task Checker
        %p.lead
          Implement your solution and check with autotests

      = yield